---
title: "Individual Clustering"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)
```

```{r, libraries}

library(Seurat)
library(cowplot)
library(SCFunctionsV3)
library(dplyr)
library(tidyr)
library(stringr)
library(tidyverse)
library(DoubletFinder)
library(pheatmap)
library(ggplot2)


### Functions
howManyCells <- function(sObj){dim(sObj)[2]}


### Functions
preDoublets <- function(seuratObj){  
    seuratObj <- NormalizeData(seuratObj)
    
    seuratObj <- ScaleData(seuratObj)
    seuratObj <- FindVariableFeatures(seuratObj, 
                                      x.low.cutoff = 0.0125, 
                                      y.cutoff = 0.25, 
                                      do.plot=FALSE)
    seuratObj <- RunPCA(seuratObj, pc.genes = seuratObj@var.genes, pcs.print = 0)
    
    # set.seed(1234)
    # seuratObj <- RunTSNE(seuratObj, dims.use = 1:10, verbose=TRUE)
    return(seuratObj)
}

findDoublets <- function(seuratObj){
    
    ### calculate expected number of doublets
    nExp_poi  <- round(0.15*nrow(seuratObj@meta.data))
    
    ### predict doublets
    seuratObj <- doubletFinder_v3(seuratObj, 
                                  PCs = 1:10, 
                                  pN = 0.25, 
                                  pK = 0.01, 
                                  nExp = nExp_poi, 
                                  reuse.pANN = FALSE, 
                                  sct=FALSE)
    
    
    seuratObj@meta.data <- seuratObj@meta.data %>% 
        rename_at(vars(starts_with("DF.classifications")), 
                  funs(str_replace(., ".*", "DF.classifications"))) %>%
        rename_at(vars(starts_with("pANN")), 
                  funs(str_replace(., ".*", "pANN")))
    
    return(seuratObj) 
    
}


sObj_Filtered <- readRDS("rObjects/sObj_Filtered_all.rds")
sampleInfo <- readRDS("rObjects/sampleInfo_all.rds")

getwd()
```



```{r, eval = FALSE}
# Cluster Cells
# 3_Individual_Clustering_CellType_Predictions_Markers
```


Each sample was clustered at a resolution of 1. The clusters generated are shown below.


```{r, fig.height=15, fig.width=15}
##plot samples
plotUMAP <- function(sObj){
  day <- sObj$day %>% unique()
  p1 <- DimPlot(sObj, label = TRUE) + 
    ggtitle(paste0("Clusters day ", day))
  p2 <- DimPlot(sObj, label = TRUE, group.by = "predicted.id") + 
    ggtitle(paste0("Predicted Cell Types day ", day))
  p3 <- p1 + p2
    return(p3)}

lapply(sObj_Filtered, plotUMAP)


```









